In [4]:
#ndarray 的運算
import numpy as np

arr = np.ones(5)
print(arr * 5)

arr_1 = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr_1 * 5)

[ 5.  5.  5.  5.  5.]
[[ 5 10 15]
 [20 25 30]]


In [5]:
import numpy as np

arr_1 = np.array([
    [1,2,3],
    [4,5,6]
])

arr_2 = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr_1 * arr_2)          #這也只是在做element-wise運算，不是矩陣內積

[[ 1  4  9]
 [16 25 36]]


In [8]:
#使用內積方法
import numpy as np

arr_1 = np.array([
    [1,2],
    [4,5]
])

arr_2 = np.array([
    [1,2],
    [3,4]
])
print(arr_1 * arr_2)        #這也只是在做element-wise運算，不是矩陣內積
print(np.dot(arr_1, arr_2)) #矩陣內積
print(arr_1.dot(arr_2))     #矩陣內積
print("\n")
print(np.dot(arr_2, arr_1)) #矩陣內積
print(arr_2.dot(arr_1))     #矩陣內積

[[ 1  4]
 [12 20]]
[[ 7 10]
 [19 28]]
[[ 7 10]
 [19 28]]


[[ 9 12]
 [19 26]]
[[ 9 12]
 [19 26]]


In [26]:
#ndarray 的運算（4）
#練習計算 uTv
import numpy as np
arr_uT = np.array([4, -4, -3])
print(arr_uT)
print(arr_uT.T)

arr_v = np.array([[4],
                 [2], 
                 [4]
])
print(arr_v)
print(arr_v.T)

print(arr_uT.dot(arr_v))

[ 4 -4 -3]
[ 4 -4 -3]
[[4]
 [2]
 [4]]
[[4 2 4]]
[-4]


In [19]:
#ndarray 的運算（5）
#練習計算 A∗IA∗I 與 I∗A

import numpy as np
arr_A = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(arr_A)

arr_I = np.eye(3)
print(arr_I)

print("A˙I=")
print(np.dot(arr_A, arr_I))
print("I˙A=")
print(np.dot(arr_I, arr_A))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
A˙I=
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
I˙A=
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [24]:
#ndarray 的運算（6）
#練習計算 A∗BA∗B 與 B∗A
import numpy as np
arr_A = np.array([1,2,4,5]).reshape(2,2)
print(arr_A)

arr_B = np.array([4,3,2,1]).reshape(2,2)
print(arr_B)

print("A˙B=")
print(np.dot(arr_A, arr_B))
print("B˙A=")
print(np.dot(arr_B, arr_A))

[[1 2]
 [4 5]]
[[4 3]
 [2 1]]
A˙B=
[[ 8  5]
 [26 17]]
B˙A=
[[16 23]
 [ 6  9]]


In [ ]:
import numpy as np

arr = np.arange(10)
print(arr.shape)
arr = arr.reshape(2, 5)
print(arr.shape)
print("\n")
print(arr)
print(arr.T)
print("\n")
arr = arr.ravel()
print(arr)
print(arr.shape)
print("\n")
print(np.where(arr < 5, 99, arr))
#   np.where(判斷條件，判斷條件為True時把元素帶換成什麼，判斷條件為False時元素維持原樣)

In [35]:
#常用屬性與方法（3）
#相乘：.prod()
#加總：.sum()
#平均：.mean()
import numpy as np

arr = np.arange(1, 11).reshape(2, 5)
print(arr)
print("所有元素相乘")
print(arr.prod())
print("axis = 0 : by column相乘 ex.1*6=6,2*7=14,3*8=24")
print(arr.prod(axis = 0))
print("axis = 1 : by row相乘")
print(arr.prod(axis = 1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
所有元素相乘
3628800
axis = 0 : by column相乘 ex.1*6=6,2*7=14,3*8=24
[ 6 14 24 36 50]
axis = 1 : by row相乘
[  120 30240]


In [38]:
#常用屬性與方法（4）
#找出 unique values：np.unique()
#檢查每個元素是否包含於：np.in1d()
#連結 ndarrays：np.concatenate()      v.s. list要相連的話，用+就好了 ex. [1,2,3]+[4,5,6] == [1,2,3,4,5,6]
import numpy as np

arr = np.arange(1, 11).reshape(2, 5)
print(arr)
print("所有元素相乘")
print(arr.prod())
print("axis = 0 : by column相乘 ex.1*6=6,2*7=14,3*8=24")
print(arr.prod(axis = 0))
print("axis = 1 : by row相乘")
print(arr.prod(axis = 1))
print("連結 ndarrays：np.concatenate()  v.s. list要相連的話，用+就好了 ex. [1,2,3]+[4,5,6] == [1,2,3,4,5,6]")
print( np.concatenate( [arr.prod(axis = 0), arr.prod(axis = 1)] ) )

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
所有元素相乘
3628800
axis = 0 : by column相乘 ex.1*6=6,2*7=14,3*8=24
[ 6 14 24 36 50]
axis = 1 : by row相乘
[  120 30240]
連結 ndarrays：np.concatenate()  v.s. list要相連的話，用+就好了 ex. [1,2,3]+[4,5,6] == [1,2,3,4,5,6]
[    6    14    24    36    50   120 30240]


In [55]:
#隨堂練習
#建立一個外觀為 (9, 9) 的 ndarray
#填入九九乘法表

#自己練習的版本，有錯!

import numpy as np

arr = np.zeros(81).reshape(9,9)
print(arr)

for i in np.arange(9) : 
    for j in np.arange(9) :
        i, j = (i + 1) * (j + 1)       #修正 : "  arr[i, j]  "              = (i + 1) * (j + 1)
print(arr)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]


TypeError: 'numpy.int32' object is not iterable

In [ ]:
#隨堂練習
#建立一個外觀為 (9, 9) 的 ndarray
#填入九九乘法表

#修正版!!!!!!!!!!!!!!


import numpy as np

arr = np.zeros(81).reshape(9,9)
print(arr)

for i in range(arr.shape[0]) : 
    for j in range(arr.shape[1]) :
        arr[i, j] = (i + 1) * (j + 1)
print(arr)

In [52]:
#隨堂練習
#建立一個外觀為 (9, 9) 的 ndarray
#填入九九乘法表

#使用內積

import numpy as np

arr_1 = np.arange(1,10).reshape(9, 1)
arr_2 = arr_1.T
print(np.dot(arr_1, arr_2))

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


In [67]:
#建立 Series（2）
#data 是一個 ndarray

import numpy as np
import pandas as pd

arr = np.array(("Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"))
print(type(arr))
print(arr)
print("\n")
s = pd.Series(arr)                          # 預設的索引
print(type(s))
print(s)
print("\n")
s = pd.Series(arr, index = range(11,20))    # 使用自訂的索引
print(s)
print("\n")
crew_idx = []
for i in range(9):
    crew_idx.append("crew %s" % str(i + 1))
ser = pd.Series(arr, index = crew_idx)      # 使用自訂的索引
print(ser)

<class 'numpy.ndarray'>
['Monkey D. Luffy' 'Roronoa Zoro' 'Nami' 'Usopp' 'Vinsmoke Sanji'
 'Tony Tony Chopper' 'Nico Robin' 'Franky' 'Brook']


<class 'pandas.core.series.Series'>
0      Monkey D. Luffy
1         Roronoa Zoro
2                 Nami
3                Usopp
4       Vinsmoke Sanji
5    Tony Tony Chopper
6           Nico Robin
7               Franky
8                Brook
dtype: object


11      Monkey D. Luffy
12         Roronoa Zoro
13                 Nami
14                Usopp
15       Vinsmoke Sanji
16    Tony Tony Chopper
17           Nico Robin
18               Franky
19                Brook
dtype: object


crew 1      Monkey D. Luffy
crew 2         Roronoa Zoro
crew 3                 Nami
crew 4                Usopp
crew 5       Vinsmoke Sanji
crew 6    Tony Tony Chopper
crew 7           Nico Robin
crew 8               Franky
crew 9                Brook
dtype: object


In [72]:
#建立 Series（3）
#data 是一個 dict
#預設會將 key 當作索引值

import pandas as pd

crew_dict = {
    "captain": "Monkey D. Luffy",
    "swordsman": "Roronoa Zoro",
    "navigator": "Nami",
    "sniper": "Usopp",
    "chef": "Vinsmoke Sanji",
    "doctor": "Tony Tony Chopper",
    "archaeologist": "Nico Robin",
    "shipwright": "Franky",
    "musician": "Brook"
}

s = pd.Series(crew_dict) # 會把 key 依照A~Z排序
print(s)
print("\n")

s = pd.Series(crew_dict, index = crew_dict.keys()) # 會依照 key 排序
print(s)
print("\n")

print(type(s))
print(s.index)
print(s.values)
print("從這裡可以知道panda的Series是建立在numpy的ndarray之上!")
print(type(s.index))
print(type(s.values))

archaeologist           Nico Robin
captain            Monkey D. Luffy
chef                Vinsmoke Sanji
doctor           Tony Tony Chopper
musician                     Brook
navigator                     Nami
shipwright                  Franky
sniper                       Usopp
swordsman             Roronoa Zoro
dtype: object


captain            Monkey D. Luffy
swordsman             Roronoa Zoro
navigator                     Nami
sniper                       Usopp
chef                Vinsmoke Sanji
doctor           Tony Tony Chopper
archaeologist           Nico Robin
shipwright                  Franky
musician                     Brook
dtype: object


<class 'pandas.core.series.Series'>
Index(['captain', 'swordsman', 'navigator', 'sniper', 'chef', 'doctor',
       'archaeologist', 'shipwright', 'musician'],
      dtype='object')
['Monkey D. Luffy' 'Roronoa Zoro' 'Nami' 'Usopp' 'Vinsmoke Sanji'
 'Tony Tony Chopper' 'Nico Robin' 'Franky' 'Brook']
從這裡可以知道panda的Series是建立在numpy的ndarray之上!

In [127]:
#建立 DataFrame
#用 DataFrame() 建立 DataFrame :
#      其中 data 是：
#                   一個 dict ------------>可以儲存不同的資料結構類型
#                   一個 ndarray----------> uni-variable 特性，資料結構會被轉成單一的



#2017 08 14 pyds part4    16:30   36:47前(後)

#一個DataFram是由多個Series組成的，而Series又是index跟values組成，又，values其實是ndarray的資料結構--->
# Series = pandas.index + np.ndarray---->
# Series是建立在ndarray以上的資料結構---->
#--
# |
# ->要注意資料裡面有沒有布林。
#因為布林一但在ndarray被轉換成文字之後(ndaray統一資料結構的特性)，
#會遇到一個情況 : 把文字轉回布林時一律都會得到True，那原本資料該是False都會變成True


In [126]:
#建立 DataFrame（2）
#其中 data 是一個 dict

import numpy as np
import pandas as pd

straw_hat_dict = {"name": ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"],
                  "age": [19, 21, 20, 19, 21, 17, 30, 36, 90],
                  "is_male": [True, True, False, True, True, True, False, True, True]
}

df = pd.DataFrame(straw_hat_dict) # 欄標籤預設排序
print("type(df)")
print(type(df))
print("\n")
print("df.dtypes")
print(df.dtypes)
print("\n")
#關於.dtypes(而不是.dtype) : 因為不是ndarray，可以有多種資料結構

#用 DataFrame() 建立 DataFrame
#其中 data 是：
#     一個 dict ------------>可以儲存不同的資料結構類型
#     一個 ndarray----------> uni-variable 特性，資料結構會被轉成單一的

print('建立DataFrame，其中data是一個dict : ')
print('df = pd.DataFrame(字典名稱, columns = ["name", "age", "is_male"]) --> 指定欄索引值/標籤順序  ')
df = pd.DataFrame(straw_hat_dict, columns = ["name", "age", "is_male"])   #指定欄位順序
df

type(df)
<class 'pandas.core.frame.DataFrame'>


df.dtypes
age         int64
is_male      bool
name       object
dtype: object


建立DataFrame，其中data是一個dict : 
df = pd.DataFrame(字典名稱, columns = ["name", "age", "is_male"]) --> 指定欄索引值/標籤順序  


name  age  is_male
0    Monkey D. Luffy   19     True
1       Roronoa Zoro   21     True
2               Nami   20    False
3              Usopp   19     True
4     Vinsmoke Sanji   21     True
5  Tony Tony Chopper   17     True
6         Nico Robin   30    False
7             Franky   36     True
8              Brook   90     True

In [ ]:
#建立 DataFrame（3）
#其中 data 是一個 ndarray

In [ ]:
#Data frame 的操作（3） 利用 .insert() 指定column變數新增的位置

In [ ]:
#選擇 Data frame 中的元素
#可以透過中括號 [] 選擇元素
#也可以透過 . 將變數當作屬性選擇

In [ ]:
#選擇 Data frame 中的元素（2）
#可以選擇多個變數

In [ ]:
#選擇 Data frame 中的元素（3）
#[:] 範圍切割（range slicing）支援列資料

In [93]:
#選擇 Data frame 中的元素（4）
#不同的選擇方法：
#.loc    完全以row的index跟column的標籤，做為選擇的準則
#.iloc   i for integer，只認相對位置

import pandas as pd # 引用套件並縮寫為 pd

df = pd.DataFrame(
    {"name": ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"],
     "age": [19, 21, 20, 19, 21, 17, 30, 36, 90],
     "is_male": [True, True, False, True, True, True, False, True, True]
    },
    index = list(range(5)) + list(range(10, 14))
)
print(df)

df.iloc[:2, 1:3]

    age  is_male               name
0    19     True    Monkey D. Luffy
1    21     True       Roronoa Zoro
2    20    False               Nami
3    19     True              Usopp
4    21     True     Vinsmoke Sanji
10   17     True  Tony Tony Chopper
11   30    False         Nico Robin
12   36     True             Franky
13   90     True              Brook


is_male             name
0     True  Monkey D. Luffy
1     True     Roronoa Zoro

In [129]:
#選擇 Data frame 中的元素（4）
#不同的選擇方法：

# .loc[選列 , 選行] 只認絕對索引值，   .loc    完全以row的index跟column的標籤，做為選擇的準則    
#df.loc[列的起始(絕對)索引值:列的終止(絕對)索引值, ['跳著選行的(絕對)索引值1(標籤keys: age)','跳著選行的(絕對)索引值2(標籤keys: name)',...]]
#df.loc[absolute start index : absolute end index , [跳著選行的(絕對)索引值1, 跳著選行的(絕對)索引值2] ]，loc沒有遵循end-1的慣例
#                          loc沒有遵循python的end-1的慣例，
#                             因為loc找絕對所引值阿!!! 

# .iloc[選列 , 選行]只認相對位置， .iloc   i for integer                               
#df.iloc[ [跳著選列相對索引值0, 跳著選列相對索引值6] , [跳著選行相對索引值0, 跳著選行相對索引值2] ]
#df.iloc[起始列相對索引值:終止列相對索引值 , 起始行相對索引值:終止行相對索引值]



import pandas as pd 

df = pd.DataFrame(
    {"name": ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"],
     "age": [19, 21, 20, 19, 21, 17, 30, 36, 90],
     "is_male": [True, True, False, True, True, True, False, True, True]
    },
    index = list(range(5)) + list(range(10, 14))
)
print("最初的DataFrame")
print(df)
print("\n")


#.loc
import pandas as pd # 引用套件並縮寫為 pd

df = pd.DataFrame(
    {"name": ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"],
     "age": [19, 21, 20, 19, 21, 17, 30, 36, 90],
     "is_male": [True, True, False, True, True, True, False, True, True]
    },
    index = list(range(5)) + list(range(10, 14))
)
print("df.loc[]選row的絕對索引值在7以內，且column欄位標籤是從age和name的那些資料所構成的DataFrame")
print("#df.loc[列的起始(絕對)索引值:列的終止(絕對)索引值, ['跳著選行的(絕對)索引值1(標籤keys: age)','跳著選行的(絕對)索引值2(標籤keys: name)',...]]")
print(df.loc[:7, ['age', 'name']])
#.loc    完全以 row的index 以及 column的標籤 做為選擇的準則
#選row的index在7以內，且column欄位標籤是從age到name的那些資料
#df.loc[ row start index : row end index , ['column index_1(標籤keys : age)', 'column index_2(標籤keys : name)']]
print("\n")


#.iloc
import pandas as pd

df = pd.DataFrame(
    {"name": ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"],
     "age": [19, 21, 20, 19, 21, 17, 30, 36, 90],
     "is_male": [True, True, False, True, True, True, False, True, True]
    },
    index = list(range(5)) + list(range(10, 14))
)

print("df.iloc[]選row的相對索引值在7以內，且column相對索引值從0到2的那些資料所構成的DataFrame")
print(df.iloc[:7, [0, 2]])

print("df.iloc[ [跳著選列相對索引值0, 跳著選列相對索引值6] , [跳著選行相對索引值0, 跳著選行相對索引值2] ]")
print(df.iloc[ [0,6], [0,2] ])

print("df.iloc[起始列相對索引值:終止列相對索引值 , 起始行相對索引值:終止行相對索引值]")
print(df.iloc[:7, 0:2])
# .iloc只認相對位置， .iloc   i for integer                               

print("\n")


print(df.iloc[::-1 , :])

最初的DataFrame
    age  is_male               name
0    19     True    Monkey D. Luffy
1    21     True       Roronoa Zoro
2    20    False               Nami
3    19     True              Usopp
4    21     True     Vinsmoke Sanji
10   17     True  Tony Tony Chopper
11   30    False         Nico Robin
12   36     True             Franky
13   90     True              Brook


df.loc[]選row的絕對索引值在7以內，且column欄位標籤是從age和name的那些資料所構成的DataFrame
#df.loc[列的起始(絕對)索引值:列的終止(絕對)索引值, ['跳著選行的(絕對)索引值1(標籤keys: age)','跳著選行的(絕對)索引值2(標籤keys: name)',...]]
   age             name
0   19  Monkey D. Luffy
1   21     Roronoa Zoro
2   20             Nami
3   19            Usopp
4   21   Vinsmoke Sanji


df.iloc[]選row的相對索引值在7以內，且column相對索引值從0到2的那些資料所構成的DataFrame
    age               name
0    19    Monkey D. Luffy
1    21       Roronoa Zoro
2    20               Nami
3    19              Usopp
4    21     Vinsmoke Sanji
10   17  Tony Tony Chopper
11   30         Nico Robin
df.iloc[ [跳著選列相對索引值0, 跳著選列相對索引值6] , [跳著選行相

In [64]:
#同學發問 loc  iloc
import pandas as pd 

df = pd.DataFrame(
    {"name": ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"],
     "age": [19, 21, 20, 19, 21, 17, 30, 36, 90],
     "is_male": [True, True, False, True, True, True, False, True, True]
    },
    index =  list(range(10, 14)) + list(range(5))   #要是index全部錯亂呢
)
print("最初的DataFrame")
print(df)
print("\n")

print("要是index全部錯亂，loc  iloc會出錯，所以建議重新assign索引值")
print(df.loc[ 1:13 , : ])         #會出錯，所以建議重新assign索引值



最初的DataFrame
    age  is_male               name
10   19     True    Monkey D. Luffy
11   21     True       Roronoa Zoro
12   20    False               Nami
13   19     True              Usopp
0    21     True     Vinsmoke Sanji
1    17     True  Tony Tony Chopper
2    30    False         Nico Robin
3    36     True             Franky
4    90     True              Brook


要是index全部錯亂，loc  iloc會出錯，所以建議重新assign索引值
Empty DataFrame
Columns: [age, is_male, name]
Index: []


In [47]:
#選擇 Data frame 中的元素（5）
#可以使用布林值篩選

import pandas as pd # 引用套件並縮寫為 pd

df = pd.DataFrame(
    {"name": ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"],
     "age": [19, 21, 20, 19, 21, 17, 30, 36, 90],
     "is_male": [True, True, False, True, True, True, False, True, True]
    }
)
# 篩選小於 30 歲的船員
age_filter = df.age < 30     # age_filter  <class 'pandas.core.series.Series'>
print(type(age_filter))

df[age_filter]

<class 'pandas.core.series.Series'>


age  is_male               name
0   19     True    Monkey D. Luffy
1   21     True       Roronoa Zoro
2   20    False               Nami
3   19     True              Usopp
4   21     True     Vinsmoke Sanji
5   17     True  Tony Tony Chopper

In [101]:
#選擇 Data frame 中的元素（6）
#請同學練習使用布林值篩選出草帽海賊團的熟男：
#age >= 30
#is_male == True

import pandas as pd # 引用套件並縮寫為 pd

df = pd.DataFrame(
    {"name": ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"],
     "age": [19, 21, 20, 19, 21, 17, 30, 36, 90],
     "is_male": [True, True, False, True, True, True, False, True, True]
    }
)

filter = ((df.age >= 30) & (df.is_male == True))
print(df[filter])
print("\n")

filter_1 = ((df["age"] >= 30) & (df["is_male"] == True))
print(df[filter_1])

   age  is_male    name
7   36     True  Franky
8   90     True   Brook


   age  is_male    name
7   36     True  Franky
8   90     True   Brook


In [60]:
#了解 DataFrame 的概觀
#.shape
#.index
#.columns
#.info()
#.count()           df.count() : 每個變數有幾個data point

import pandas as pd 

df = pd.DataFrame(
    {"name": ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"],
     "age": [19, 21, 20, 19, 21, 17, 30, 36, 90],
     "is_male": [True, True, False, True, True, True, False, True, True]
    }
)

print("df.index")
print(df.index)   #RangeIndex(start=0, stop=9, step=1) 索引值從0到8間隔為1
print("\n")

print("df.columns")
print(df.columns)
print("\n")

print("df.info()")
print(df.info())
print("\n")

print("df.count() : 每個變數有幾個data point")
print(df.count())
print("\n")


df.index
RangeIndex(start=0, stop=9, step=1)


df.columns
Index(['age', 'is_male', 'name'], dtype='object')


df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
age        9 non-null int64
is_male    9 non-null bool
name       9 non-null object
dtypes: bool(1), int64(1), object(1)
memory usage: 157.0+ bytes
None


df.count() : 每個變數有幾個data point
age        9
is_male    9
name       9
dtype: int64




In [63]:
#了解 DataFrame 的概觀（2）
#.head()      : 預設前5個列的觀測值
#.tail()
#.describe()  : 似R語言的summary方法，整理一個簡單的敘述統計表格

print("df.head()回傳前幾列的觀察值 (預設為前5列的觀測值)")
print(df.head())
print(df.head(5))
print("\n")
print("df.tail()回傳後幾列的觀察值 (預設為前5列的觀測值)")
print(df.tail())
print(df.tail(5))
print("\n")
print("df.describe()整理一個簡單的敘述統計表格 (似R語言的summary方法)")
print(df.describe())

.head()回傳前幾列的觀察值 (預設為前5列的觀測值)
   age  is_male             name
0   19     True  Monkey D. Luffy
1   21     True     Roronoa Zoro
2   20    False             Nami
3   19     True            Usopp
4   21     True   Vinsmoke Sanji
   age  is_male             name
0   19     True  Monkey D. Luffy
1   21     True     Roronoa Zoro
2   20    False             Nami
3   19     True            Usopp
4   21     True   Vinsmoke Sanji


.tail()回傳後幾列的觀察值 (預設為前5列的觀測值)
   age  is_male               name
4   21     True     Vinsmoke Sanji
5   17     True  Tony Tony Chopper
6   30    False         Nico Robin
7   36     True             Franky
8   90     True              Brook
   age  is_male               name
4   21     True     Vinsmoke Sanji
5   17     True  Tony Tony Chopper
6   30    False         Nico Robin
7   36     True             Franky
8   90     True              Brook


.describe()整理一個簡單的敘述統計表格 (似R語言的summary方法)
             age
count   9.000000
mean   30.333333
std    23.205603
min    17.

In [77]:
#排序 DataFrame
#.sort_index()     : df.sort_index(axis = __ , 預設ascending = True)  ---->axis選擇0是列，1是行
#.sort_values()    : df.sort_values(by = "條件(某一行的key)")
#                    df.sort_values(by = ["先按條件1排好", "再按條件2排好"], 預設ascending = True)   ---->條件為某一行的key


import pandas as pd # 引用套件並縮寫為 pd

df = pd.DataFrame(
    {"name": ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"],
     "age": [19, 21, 20, 19, 21, 17, 30, 36, 90],
     "is_male": [True, True, False, True, True, True, False, True, True]
    }, columns = ['name', 'age', 'is_male']
)

print("df.sort_index(axis = __ , 預設ascending = True)  ---->axis選擇0是列，1是行")
print(df.sort_index(axis = 0, ascending = False))
print("\n")

print('df.sort_values(by = ["先按條件1排好", "再按條件2排好"], 預設ascending = True)   ---->條件為某一行的key')
print(df.sort_values(by = ["is_male", "age"], ascending = True))
print('df.sort_values(by = ["先按條件1排好", "再按條件2排好"], ascending = False)   ---->條件為某一行的key')
print(df.sort_values(by = ["is_male", "age"], ascending = False))

df.sort_index(axis = __ , 預設ascending = True)  ---->axis選擇0是列，1是行
                name  age  is_male
8              Brook   90     True
7             Franky   36     True
6         Nico Robin   30    False
5  Tony Tony Chopper   17     True
4     Vinsmoke Sanji   21     True
3              Usopp   19     True
2               Nami   20    False
1       Roronoa Zoro   21     True
0    Monkey D. Luffy   19     True


df.sort_values(by = ["先按條件1排好", "再按條件2排好"], 預設ascending = True)   ---->條件為某一行的key
                name  age  is_male
2               Nami   20    False
6         Nico Robin   30    False
5  Tony Tony Chopper   17     True
0    Monkey D. Luffy   19     True
3              Usopp   19     True
1       Roronoa Zoro   21     True
4     Vinsmoke Sanji   21     True
7             Franky   36     True
8              Brook   90     True
df.sort_values(by = ["先按條件1排好", "再按條件2排好"], ascending = False)   ---->條件為某一行的key
                name  age  is_male
8              Brook   90     True

In [136]:
#處理遺漏值
#.dropna()
#.fillna() : 『fillna』可以一次性解決，常以整行的平均數或眾數或中位數來替換缺失值
#Q : 如果一行裡面有多個遺漏值，可是想用不同的資料來填補怎麼辦




#--------------------------.dropna()--------------------------

import pandas as pd
import numpy as np

name = ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook", np.NaN]
age = [19, 21, 20, 19, 21, 17, 30, 36, np.NaN, np.NaN]
is_male = [True, True, False, True, True, np.NaN, False, True, True, np.NaN]

straw_hat_dict = {"name": name,
                  "age": age,
                  "is_male": is_male
}

print("有遺漏值的Datafram")
df = pd.DataFrame(straw_hat_dict, columns = ["name", "age", "is_male"])
print(df)
print("\n")

print("剔除遺漏值 : df.dropna(how = 'all')  所有觀測值都是NA的那一列才會被剔除")
print(df.dropna(how = 'all'))
print("\n")
print("剔除遺漏值 : df.dropna(how = 'any')  任何觀測值都是NA的那一列才會被剔除")
print(df.dropna(how = 'any'))
print("\n")

#--------------------------.fillna()--------------------------

import pandas as pd
import numpy as np

name = ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook", np.NaN]
age = [19, 21, 20, 19, 21, 17, 30, 36, np.NaN, np.NaN]
is_male = [True, True, False, True, True, np.NaN, False, True, True, np.NaN]

straw_hat_dict = {"name": name,
                  "age": age,
                  "is_male": is_male
}

print("有遺漏值的Datafram")
df = pd.DataFrame(straw_hat_dict, columns = ["name", "age", "is_male"])
print(df)
print("\n")

#C:\Users\JS\Anaconda3\lib\site-packages\pandas\core\frame.py in _getitem_column(self, key)
#   2067         # get column
#   2068         if self.columns.is_unique:
#-> 2069             return self._get_item_cache(key)
#   2070 
#   2071         # duplicate columns & possible reduce dimensionality


#Q : 如果一行裡面有多個遺漏值，可是想用不同的資料來填補怎麼辦 -->用.where條件判斷，分段進行
print("column填補遺漏值 : 指派df['某一行的索引值key'] = df['某一行的索引值key'].na('輸入你要的data')")
print("column 'is_male'填補遺漏值 : 指派df['is_male'] = df['is_male'].na('True')")
df["is_male"] = df["is_male"].fillna("True")
print(df)
print("\n")
print("column 'age'填補遺漏值 : 指派df['age'] = df['age'].na('90')")
df["age"] = df["age"].fillna("90")
print(df)



有遺漏值的Datafram
                name   age is_male
0    Monkey D. Luffy  19.0    True
1       Roronoa Zoro  21.0    True
2               Nami  20.0   False
3              Usopp  19.0    True
4     Vinsmoke Sanji  21.0    True
5  Tony Tony Chopper  17.0     NaN
6         Nico Robin  30.0   False
7             Franky  36.0    True
8              Brook   NaN    True
9                NaN   NaN     NaN


剔除遺漏值 : df.dropna(how = 'all')  所有觀測值都是NA的那一列才會被剔除
                name   age is_male
0    Monkey D. Luffy  19.0    True
1       Roronoa Zoro  21.0    True
2               Nami  20.0   False
3              Usopp  19.0    True
4     Vinsmoke Sanji  21.0    True
5  Tony Tony Chopper  17.0     NaN
6         Nico Robin  30.0   False
7             Franky  36.0    True
8              Brook   NaN    True


剔除遺漏值 : df.dropna(how = 'any')  任何觀測值都是NA的那一列才會被剔除
              name   age is_male
0  Monkey D. Luffy  19.0    True
1     Roronoa Zoro  21.0    True
2             Nami  20.0   False
3            

In [132]:
#合併
#pandas.concat()
#垂直合併
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {"name": ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"],
     "age": [19, 21, 20, 19, 21, 17, 30, 36, 90],
     "is_male": [True, True, False, True, True, True, False, True, True]
    }, columns = ['name', 'age', 'is_male']
)

#help(pd.concat)

upper_df = df.loc[ :4 , : ]
lower_df = df.loc[5:  , : ]
print(upper_df)
print("\n")
print(lower_df)
print("\n")
print(pd.concat([upper_df, lower_df], axis = 0))


              name  age  is_male
0  Monkey D. Luffy   19     True
1     Roronoa Zoro   21     True
2             Nami   20    False
3            Usopp   19     True
4   Vinsmoke Sanji   21     True


                name  age  is_male
5  Tony Tony Chopper   17     True
6         Nico Robin   30    False
7             Franky   36     True
8              Brook   90     True


                name  age  is_male
0    Monkey D. Luffy   19     True
1       Roronoa Zoro   21     True
2               Nami   20    False
3              Usopp   19     True
4     Vinsmoke Sanji   21     True
5  Tony Tony Chopper   17     True
6         Nico Robin   30    False
7             Franky   36     True
8              Brook   90     True


In [122]:
df = pd.DataFrame(
    {"name": ["Monkey D. Luffy", "Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"],
     "age": [19, 21, 20, 19, 21, 17, 30, 36, 90],
     "is_male": [True, True, False, True, True, True, False, True, True]
    }, columns = ['name', 'age', 'is_male']
)

upper_df = df.loc[:4, :]
lower_df = df.loc[5:, :]
pd.concat([upper_df, lower_df], axis = 0)

name  age  is_male
0    Monkey D. Luffy   19     True
1       Roronoa Zoro   21     True
2               Nami   20    False
3              Usopp   19     True
4     Vinsmoke Sanji   21     True
5  Tony Tony Chopper   17     True
6         Nico Robin   30    False
7             Franky   36     True
8              Brook   90     True

In [124]:
pd.joined = pd.merge(left_df, right_df)

NameError: name 'left_df' is not defined